/**
 * @defgroup 
 * DbgDriver Debug Services
 * @ingroup  PwrMgt
 */

/**
 * @addtogroup DbgDriver Debug Services
 * @{
 */

/**
 * @file drv_mapping.h  definitions of Linker defined addresses 
 *       or values
 *       
 *
 */

#ifndef DRV_MAPPING_H
#define DRV_MAPPING_H

#if !(ICERA_SDK_EV_AT_LEAST(4,11,'a'))

#define __top_a0_gmem0_data __top_a0_gmem_data
#define __base_a0_gmem0_data __base_a0_gmem_data

#define __top_a1_gmem0_data __top_a1_gmem_data
#define __base_a1_gmem0_data __base_a1_gmem_data

#define __top_a2_gmem0_data __top_a2_gmem_data
#define __base_a2_gmem0_data __base_a2_gmem_data

#define __top_a0_gmem0_bss __top_a0_gmem_bss
#define __base_a0_gmem0_bss __base_a0_gmem_bss

#define __top_a1_gmem0_bss __top_a1_gmem_bss
#define __base_a1_gmem0_bss __base_a1_gmem_bss

#define __top_a2_gmem0_bss __top_a2_gmem_bss
#define __base_a2_gmem0_bss __base_a2_gmem_bss

#define __load_start_dmem0_data_always_resident __load_start_dmem_data_always_resident
#define __load_start_uncached_gmem0_text __load_start_uncached_gmem_text

#define __load_start_gmem0_text __load_start_gmem_text
#define __load_stop_gmem0_text __load_stop_gmem_text

#endif


/* Symbols generated by link script */
extern uint32 __ro_cached_start;           /** start address of the read-only memory (cached)  */
extern uint32 __ro_cached_end;             /** end address of the read-only memory (cached)  */

extern uint32 __base_a0_cached;       /** start address of the DXP0 cached init data section */
extern uint32 __base_a1_cached;       /** start address of the DXP1 cached init data section */
extern uint32 __top_a0_cached;        /** top address of the DXP0 cached init data section */
extern uint32 __top_a1_cached;        /** top address of the DXP1 cached init data section */

extern uint32 __base_a0_cached_bss;        /** start address of the DXP0 bss section */
extern uint32 __base_a1_cached_bss;        /** start address of the DXP1 bss section */
extern uint32 __top_a0_cached_bss;         /** top address of the DXP0 bss section */
extern uint32 __top_a1_cached_bss;         /** top address of the DXP1 bss section */
extern uint32 __base_a2_cached;
extern uint32 __top_a2_cached;         /** top address of the cached init data section */
extern uint32 __base_a2_cached_bss;
extern uint32 __top_a2_cached_bss;         /** top address of the DXP2 bss section */

extern uint32      __top_a0_gmem0_data;
extern uint32      __base_a0_gmem0_data;

extern uint32      __top_a1_gmem0_data;
extern uint32      __base_a1_gmem0_data;

extern uint32      __top_a2_gmem0_data;
extern uint32      __base_a2_gmem0_data;

extern uint32      __top_a0_gmem0_bss;
extern uint32      __base_a0_gmem0_bss;

extern uint32      __top_a1_gmem0_bss;
extern uint32      __base_a1_gmem0_bss;

extern uint32      __top_a2_gmem0_bss;
extern uint32      __base_a2_gmem0_bss;

extern uint32 __load_start_rc_data;
extern uint32 __load_stop_rc_data;
extern uint32 __load_start_rc_bss;
extern uint32 __load_stop_rc_bss;

extern uint32 __dp0;
extern uint32 __dp1;
extern uint32 __dp2;
extern uint32 __rel_size;

extern uint32 __load_start_gmem0_text;
extern uint32 __load_stop_gmem0_text;

extern uint8 __extmem_size;    /* defined in the makefile as command-line option to the linker */


extern uint32  __heap_space;

extern uint32  __heap_space0;
extern uint32 __size0;
extern uint32  __heap_space1;
extern uint32 __size1;
extern uint32  __heap_space2;
extern uint32  __size2;

/* linker definitions for newer SDK */
extern uint32 __load_start_dmem0_data_always_resident;
extern uint32 __load_start_dmem2_data_always_resident;
extern uint32 __load_start_uncached_gmem0_text;


#endif

/** @} END OF FILE */
