
# Author:      joashr
#
# Created:     21/11/2013



# ********************************************************************************************
# Error table definition
# ********************************************************************************************

# Jenkins flash error codes
ERRCODE_SUCCESS                      = 0
ERRCODE_COM_PORT_DETECT              = 100
ERRCODE_AT_PORT                      = 101
ERRCODE_WRONG_MODE                   = 102
ERRCODE_FLASH_FAILURE                = 103
ERRCODE_NO_RISTR_PKG                 = 104
ERRCODE_URL_WRONG_FORMAT             = 105
ERRCODE_BRANCH_NOT_SUPPORTED         = 106
ERRCODE_CHECK_PKG_CL_FAIL            = 107
ERRCODE_DOWNLOAD_RISTR_PKG_FAIL      = 108
ERRCODE_P4WEBREV_DOWNLOAD_FAIL       = 109
ERRCODE_VERDICT_FILE_OPEN_FAIL       = 110
ERRCODE_PSU_COMM_ERR                 = 111
ERRCODE_TEST_SUMMARY_FILE_IO_FAIL    = 112
ERRCODE_TEST_FAIL                    = 113
ERRCODE_TEST_INCONCLUSIVE            = 114
ERRCODE_INVALID_VERDICT              = 115
ERRCODE_FLASH_TIMEOUT_ERROR          = 116
ERRCODE_STATUS_FILE_OPEN_FAIL        = 117
ERRCODE_DOWNLOAD_GENERIC_FAIL        = 118
ERRCODE_SUMMARY_FILE_NOT_FOUND       = 119
ERRCODE_TEST_SYSTEM_BREAK_POINT      = 120
ERRCODE_UNKNOWN_JOBTYPE              = 121
ERRCODE_COMMAAND_LINE_OPTION_FAIL    = 122
ERRCODE_IMPORT_ERROR                 = 123
ERRCODE_UNSUPPORTED_OS_PLATFORM      = 124
ERRCODE_BOOT_LOADER_MODE_FAIL        = 125
ERRCODE_MODE_SWITCH_FAIL             = 126
ERRCODE_COREDUMP_TIMEOUT             = 127
ERRCODE_TEST_CONFIG_XML_NOT_FOUND    = 128
ERRCODE_UNSUPPORTED_RAT              = 129
ERRCODE_UNSUPPORTED_VARIANT          = 130
ERRCODE_REGEX                        = 131
ERRCODE_NO_TEST_SUMMARY_FILE         = 132
ERRCODE_INVALID_TEST_CONFIG_PARAM    = 133


ERRCODE_UNHANDLED_EXECEPTION         = 200


error_table={
  ERRCODE_SUCCESS                     : 'PASS',
  ERRCODE_COM_PORT_DETECT             : 'COM_PORT_DETECT_FAIL',
  ERRCODE_AT_PORT                     : 'AT_PORT_DETECT_FAIL',
  ERRCODE_WRONG_MODE                  : 'MODEM_MODE_FAIL',
  ERRCODE_FLASH_FAILURE               : 'GENERIC_FLASH_FAILURE',
  ERRCODE_NO_RISTR_PKG                : 'NO_RISTRETTO_PKG',
  ERRCODE_URL_WRONG_FORMAT            : 'URL_INCORRECT_FORMAT',
  ERRCODE_BRANCH_NOT_SUPPORTED        : 'BRANCH_NOT_SUPPORTED',
  ERRCODE_CHECK_PKG_CL_FAIL           : 'CHECK_PKG_FAIL',
  ERRCODE_DOWNLOAD_RISTR_PKG_FAIL     : 'DOWNLOAD_RISTR_PKG_FAIL',
  ERRCODE_P4WEBREV_DOWNLOAD_FAIL      : 'DOWNLOAD_P4WEBREV_FAIL',
  ERRCODE_VERDICT_FILE_OPEN_FAIL      : 'VERDICT_FILE_OPEN_FAIL',
  ERRCODE_PSU_COMM_ERR                : 'PSU_COMM_ERR',
  ERRCODE_TEST_SUMMARY_FILE_IO_FAIL   : 'TEST_SUMMARY_FILE_IO_FAIL',
  ERRCODE_TEST_FAIL                   : 'TEST_FAIL',
  ERRCODE_TEST_INCONCLUSIVE           : 'TEST_INCONCLUSIVE',
  ERRCODE_INVALID_VERDICT             : 'INVALID_VERDICT',
  ERRCODE_FLASH_TIMEOUT_ERROR         : 'SOFTWARE_BUILD_FLASH_TIMEOUT',
  ERRCODE_STATUS_FILE_OPEN_FAIL       : 'STATUS_FILE_OPEN_FAIL',
  ERRCODE_DOWNLOAD_GENERIC_FAIL       : 'DOWNLOAD_GENERIC_FAIL',
  ERRCODE_SUMMARY_FILE_NOT_FOUND      : 'SUMMARY_FILE_NOT_FOUND',
  ERRCODE_TEST_SYSTEM_BREAK_POINT     : 'TEST_SYSTEM_DEBUG_BREAK_POINT',
  ERRCODE_UNKNOWN_JOBTYPE             : 'UNSUPPORTED_JOB_TYPE',
  ERRCODE_COMMAAND_LINE_OPTION_FAIL   : 'COMMAND_LINE_OPTION_DECODE_FAIL',
  ERRCODE_IMPORT_ERROR                : 'FILE_MODULE_IMPORT_ERROR',
  ERRCODE_UNSUPPORTED_OS_PLATFORM     : 'UNSUPPORTED_OS_PLATFORM',
  ERRCODE_BOOT_LOADER_MODE_FAIL       : 'BOOT_LOADER_MODE_CMD_FAIL',
  ERRCODE_MODE_SWITCH_FAIL            : 'MODEM_MODE_SWITCH_FAIL',
  ERRCODE_COREDUMP_TIMEOUT            : 'COREDUMP_COLLECT_TIMEOUT',
  ERRCODE_UNSUPPORTED_RAT             : 'UNSUPPORTED_RAT_SELECTION',
  ERRCODE_UNSUPPORTED_VARIANT         : 'ERRCODE_UNSUPPORTED_VARIANT',
  ERRCODE_REGEX                       : 'ERRCODE_REGULAR_EXPRESSION',
  ERRCODE_NO_TEST_SUMMARY_FILE        : 'NO_TEST_SUMMARY_FILE',
  ERRCODE_TEST_CONFIG_XML_NOT_FOUND   : 'ERRCODE_TEST_CONFIG_XML_NOT_FOUND',
  ERRCODE_INVALID_TEST_CONFIG_PARAM   : 'ERRCODE_INVALID_TEST_CONFIG_PARAM',

  ERRCODE_UNHANDLED_EXECEPTION        : 'UNHANDLED_EXECEPTION'

}

